# Generated by Django 4.1.3 on 2023-01-22 20:39

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Blog',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('featured_image', models.ImageField(blank=True, null=True, upload_to='')),
                ('title', models.CharField(blank=True, max_length=255, null=True)),
                ('message', models.TextField(blank=True, null=True)),
                ('created', models.DateTimeField(auto_now_add=True, null=True)),
            ],
        ),
        migrations.CreateModel(
            name='Department',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name_of_department', models.CharField(blank=True, max_length=255, null=True)),
                ('HOD', models.CharField(blank=True, max_length=255, null=True)),
                ('featured_image', models.ImageField(blank=True, max_length=255, null=True, upload_to='')),
                ('description', models.TextField(blank=True, max_length=255, null=True)),
            ],
        ),
        migrations.CreateModel(
            name='Event',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('event_name', models.CharField(blank=True, max_length=255, null=True)),
                ('event_date', models.DateField(blank=True, null=True)),
                ('created', models.DateTimeField(auto_now_add=True, null=True)),
            ],
        ),
        migrations.CreateModel(
            name='School_Informations',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('school_name', models.CharField(blank=True, max_length=255, null=True)),
                ('vision', models.TextField(blank=True, null=True)),
                ('mission', models.TextField(blank=True, null=True)),
                ('motto', models.CharField(blank=True, max_length=255, null=True)),
                ('school_history', models.TextField(blank=True, null=True)),
                ('school_location', models.CharField(blank=True, max_length=255, null=True)),
                ('email', models.CharField(blank=True, max_length=255, null=True)),
                ('first_contact', models.IntegerField(blank=True, max_length=50, null=True)),
                ('second_contact', models.IntegerField(blank=True, max_length=50, null=True)),
            ],
        ),
        migrations.CreateModel(
            name='Staff',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(blank=True, max_length=255)),
                ('status', models.CharField(blank=True, choices=[('Teaching Staff', 'Teaching Staff'), ('Non-Teaching Staff', 'Non-Teaching Staff')], max_length=255)),
                ('position', models.CharField(blank=True, choices=[('Montessori', 'Montessori'), ('Lower Primary', 'Lower Primary'), ('Upper Primary', 'Upper Primary'), ('JHS', 'JHS')], max_length=255)),
                ('contact', models.CharField(blank=True, max_length=255, null=True)),
                ('email', models.EmailField(blank=True, max_length=255, null=True)),
                ('location', models.CharField(blank=True, max_length=255)),
                ('staff_image', models.ImageField(blank=True, null=True, upload_to='')),
                ('date_of_assumption', models.DateField(blank=True, null=True)),
            ],
        ),
    ]
