# Generated by Django 4.1.3 on 2023-01-22 20:47

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('website', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='School_Information',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('school_name', models.CharField(blank=True, max_length=255, null=True)),
                ('vision', models.TextField(blank=True, null=True)),
                ('mission', models.TextField(blank=True, null=True)),
                ('motto', models.CharField(blank=True, max_length=255, null=True)),
                ('school_history', models.TextField(blank=True, null=True)),
                ('school_location', models.CharField(blank=True, max_length=255, null=True)),
                ('email', models.CharField(blank=True, max_length=255, null=True)),
                ('first_contact', models.IntegerField(blank=True, null=True)),
                ('second_contact', models.IntegerField(blank=True, null=True)),
            ],
        ),
        migrations.DeleteModel(
            name='School_Informations',
        ),
    ]
