# Generated by Django 4.1.3 on 2023-01-22 23:54

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('website', '0002_school_information_delete_school_informations'),
    ]

    operations = [
        migrations.CreateModel(
            name='Officer',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('head_teacher', models.CharField(blank=True, max_length=255, null=True)),
                ('lower_primary_hod', models.CharField(blank=True, max_length=255, null=True)),
                ('upper_primary_hod', models.CharField(blank=True, max_length=255, null=True)),
                ('jhs', models.CharField(blank=True, max_length=255, null=True)),
                ('accountant', models.CharField(blank=True, max_length=255, null=True)),
                ('secretary', models.CharField(blank=True, max_length=255, null=True)),
            ],
        ),
        migrations.AlterField(
            model_name='department',
            name='name_of_department',
            field=models.CharField(blank=True, choices=[('Montessori', 'Montessori'), ('Lower Primary', 'Lower Primary'), ('Upper Primary', 'Upper Primary'), ('JHS', 'JHS')], max_length=255, null=True),
        ),
    ]
