# Generated by Django 4.1.3 on 2023-01-23 00:10

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('website', '0003_officer_alter_department_name_of_department'),
    ]

    operations = [
        migrations.RenameField(
            model_name='staff',
            old_name='position',
            new_name='department',
        ),
        migrations.AddField(
            model_name='department',
            name='created',
            field=models.DateTimeField(auto_now_add=True, null=True),
        ),
    ]
