# Generated by Django 4.1.3 on 2023-01-23 02:18

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('website', '0004_rename_position_staff_department_department_created'),
    ]

    operations = [
        migrations.CreateModel(
            name='Team_Members',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('portfolio', models.CharField(blank=True, choices=[('Proprietor', 'Proprietor'), ('Head Teacher', 'Head Teacher'), ('Executive Secretary', 'Executive Secretary'), ('Accountant', 'Accountant')], max_length=255, null=True)),
                ('name', models.CharField(blank=True, max_length=255, null=True)),
                ('featured_image', models.ImageField(blank=True, max_length=500, null=True, upload_to='')),
                ('facebook_link', models.URLField(blank=True, max_length=500, null=True)),
                ('instagram_link', models.URLField(blank=True, max_length=500, null=True)),
                ('linkedIn_link', models.URLField(blank=True, max_length=500, null=True)),
            ],
        ),
        migrations.DeleteModel(
            name='Officer',
        ),
    ]
