# Generated by Django 4.1.3 on 2023-01-23 02:20

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('website', '0005_team_members_delete_officer'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='Team_Members',
            new_name='Team_Member',
        ),
    ]
