# Generated by Django 4.1.3 on 2023-01-23 22:46

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('website', '0006_rename_team_members_team_member'),
    ]

    operations = [
        migrations.AlterField(
            model_name='staff',
            name='department',
            field=models.CharField(blank=True, choices=[('Montessori', 'Montessori'), ('Lower Primary', 'Lower Primary'), ('Upper Primary', 'Upper Primary'), ('JHS', 'JHS'), ('Non-Teaching', 'Non-Teaching')], max_length=255),
        ),
    ]
