# Generated by Django 4.1.3 on 2023-01-23 23:52

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('website', '0007_alter_staff_department'),
    ]

    operations = [
        migrations.AlterField(
            model_name='team_member',
            name='linkedIn_link',
            field=models.ImageField(blank=True, default='logo.jpg', null=True, upload_to=''),
        ),
    ]
