# Generated by Django 4.1.3 on 2023-01-27 02:28

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('website', '0008_alter_team_member_linkedin_link'),
    ]

    operations = [
        migrations.RenameField(
            model_name='department',
            old_name='featured_image',
            new_name='HOD_featured_image',
        ),
        migrations.AddField(
            model_name='department',
            name='department_featured_image',
            field=models.ImageField(blank=True, max_length=255, null=True, upload_to=''),
        ),
    ]
