# Generated by Django 4.1.3 on 2023-01-30 10:41

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('website', '0009_rename_featured_image_department_hod_featured_image_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='team_member',
            name='linkedIn_link',
            field=models.URLField(blank=True, max_length=500, null=True),
        ),
    ]
