# Generated by Django 4.1.3 on 2023-01-30 15:45

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('website', '0010_alter_team_member_linkedin_link'),
    ]

    operations = [
        migrations.AddField(
            model_name='team_member',
            name='contact',
            field=models.IntegerField(blank=True, max_length=30, null=True),
        ),
    ]
