# Generated by Django 4.1.3 on 2023-01-30 16:52

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('website', '0011_team_member_contact'),
    ]

    operations = [
        migrations.AlterField(
            model_name='department',
            name='HOD_featured_image',
            field=models.ImageField(blank=True, default='logo.jpg', max_length=255, null=True, upload_to=''),
        ),
        migrations.AlterField(
            model_name='department',
            name='department_featured_image',
            field=models.ImageField(blank=True, default='logo.jpg', max_length=255, null=True, upload_to=''),
        ),
    ]
