# Generated by Django 4.1.3 on 2023-01-30 18:08

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('website', '0012_alter_department_hod_featured_image_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='team_member',
            name='contact',
            field=models.IntegerField(blank=True, null=True),
        ),
    ]
