# Generated by Django 4.1.3 on 2023-02-07 15:42

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('website', '0014_alter_department_name_of_department'),
    ]

    operations = [
        migrations.AlterField(
            model_name='department',
            name='name_of_department',
            field=models.CharField(blank=True, choices=[('Montessori', 'Montessori'), ('Lower Primary', 'Lower Primary'), ('Upper Primary', 'Upper Primary'), ('JHS', 'JHS')], max_length=255, null=True),
        ),
    ]
