# Generated by Django 4.1.3 on 2023-02-14 23:21

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('dashboard', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='sms',
            name='date',
            field=models.DateTimeField(auto_now_add=True),
        ),
    ]
